name: 'Cocos Creator Build'
description: 'A github action for cocos creator build'
author: ''

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'activity'
  color: 'blue'

# Define your inputs here.
inputs:
  cocos_url:
    required: true
    description: 'cocos creator download urls'
    default: ''

  project_path:
    required: false
    description: 'project path for build'
    default: './'

  build_conf:
    required: false
    description: 'build conf json file'
    default: './build_conf.json'

# Define your outputs here.
#outputs:
#  time:
#    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
