name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - develop
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run build && npm run format && npm run lint && npm run package
  # - run: |
  #     npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    # needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          cocos-version: '2.4.3'
